/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sept18;

import java.util.Random;

public class App {
  public String getGreeting() {
    int rand = new java.util.Random().nextInt();
		int random = new Random().nextInt();
    return "Hello World! This is a random number: " + rand +" and this is the class import version: "+ random;
  }
	public String Lesson2() {
		String has = "15 Constructors";
		String isempty = "no key value mapping pair";
		String isblank = "only whitespace in string detector";
		String answer = "remove whitespace ebfore using isblank";
		return has + isempty + isblank + answer;
	}
	public void Lesson3() {
		String s1  = new String("fun");
		String s2  = new String("with");
		String s3;
		System.out.println(s1);
		System.out.println(s2);
		s3 = s2;
		System.out.println(s3);
		s3 = s1; 
		System.out.println(s3);
		s1 ="Strings";
		System.out.println(s3);
	}
	public void Lesson4() {
		String s1 = "Fun";
		String s2 = "With";
		String s3 = "Fun";
		String s4 = new String("Fun");
		System.out.println(s1==s1);
		System.out.println(s1==s2);
		System.out.println(s1==s3);
		System.out.println(s1==s4);

		
	}
  public static void main(String[] args) {
		App namehere = new App();
		namehere.Lesson4();
  }
}
