/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloworld;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
				
        System.out.println(new App().getGreeting());
        System.out.println("this is another test");
				System.out.println("hello world again for the second time");
				for (int i = 0; i < 10; i++) {
					System.out.println(i);
				}
    }
}
